// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// SessionManager is an autogenerated mock type for the SessionManager type
type SessionManager struct {
	mock.Mock
}

// NewST provides a mock function with given fields:
func (_m *SessionManager) NewST() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ReadCookie provides a mock function with given fields: w, r
func (_m *SessionManager) ReadCookie(w http.ResponseWriter, r *http.Request) (string, error) {
	ret := _m.Called(w, r)

	var r0 string
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) string); ok {
		r0 = rf(w, r)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request) error); ok {
		r1 = rf(w, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetCookie provides a mock function with given fields: w, sessionToken
func (_m *SessionManager) SetCookie(w http.ResponseWriter, sessionToken string) {
	_m.Called(w, sessionToken)
}
